#!/bin/sh /etc/rc.common

# rc.common reads these init-script metadata variables outside this file.
# shellcheck disable=SC2034
START=99
# shellcheck disable=SC2034
USE_PROCD=1

# These dependencies are installed by OpenWrt and are not present on the host.
# shellcheck disable=SC1091
. /lib/functions.sh
# shellcheck disable=SC1091
. /usr/share/easytier/firewall.sh
# shellcheck disable=SC1091
. /usr/share/easytier/service.sh
